// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZE6FCl26Agc3CCapTMR7jUE8CrdsUk-o',
    appId: '1:279757870757:web:91b66a7d8f1d675f681f4c',
    messagingSenderId: '279757870757',
    projectId: 'assignmentmessengerapp',
    authDomain: 'assignmentmessengerapp.firebaseapp.com',
    storageBucket: 'assignmentmessengerapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx1kSOGWWMyCYgeRlp7eBSGshzd6sLh5M',
    appId: '1:279757870757:android:6f1fb510278876d6681f4c',
    messagingSenderId: '279757870757',
    projectId: 'assignmentmessengerapp',
    storageBucket: 'assignmentmessengerapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQYVFfW2WCCicGDqGESV-QIz_lM4qGidE',
    appId: '1:279757870757:ios:50c6a3259f7cf327681f4c',
    messagingSenderId: '279757870757',
    projectId: 'assignmentmessengerapp',
    storageBucket: 'assignmentmessengerapp.appspot.com',
    iosBundleId: 'com.example.assignmentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQYVFfW2WCCicGDqGESV-QIz_lM4qGidE',
    appId: '1:279757870757:ios:1a9b7c57638fde9c681f4c',
    messagingSenderId: '279757870757',
    projectId: 'assignmentmessengerapp',
    storageBucket: 'assignmentmessengerapp.appspot.com',
    iosBundleId: 'com.example.assignmentApp.RunnerTests',
  );
}
